#!/bin/bash
export CURRENT_UID=$(id -u):$(id -g)

cd ./backend/

curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get update

sudo apt-get install -y nodejs yarn

yarn ––version

yarn add global @nestjs/cli
