version: "3.2"
services:
  da_redis:
    container_name: da_redis
    image: "redis:alpine"
    command: redis-server --requirepass changeme
    ports:
      - "6379:6379"
    volumes:
      - ${APP_SRC}/../docker/:/usr/local/etc/redis/
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4

  da_adminer:
    container_name: da_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      node_net:
        ipv4_address: 172.28.1.7
  
  da_db:
    container_name: da_db
    image: postgres:9.6.2-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: da
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      node_net:
        ipv4_address: 172.28.1.6
  
  da_node:
    container_name: da_node
    build:
      context: ./../
      dockerfile: ./docker/containers/node/Dockerfile
    working_dir: /var/www
    ports:
      - 30001:3000
    volumes:
      - /d/dev/projects/da/da-fr:/var/www
    depends_on:
      - da_db
      - da_redis
    command: sh -c "yarn install & yarn start:dev"
    networks:
      node_net:
        ipv4_address: 172.28.1.9

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  pgdata: